server:
  port: 9999

spring:
  h2:
    console.enabled: true
    jpa:
      show-sql: true
  #    hibernate:
  #      ddl-auto: create

  datasource:
    url: "jdbc:h2:mem:inditex;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"